### ISSUE TITLE
Confused about within-view fusion

### ISSUE THREAD

**Issue by AaronXenos** [ayushjain1144/odin#11]
In paper, what does "Within-view 2D fusion" do exactly?

"pass it through the full backbone to obtain 2D features at multiple scales"

Difference with "Cross-scale fusion"?

**Comment by ayushjain1144** [comment]
"within view 2D fusion" basically means some operations that involve pixels coming from a single view-point. For us, this concretely means passing the RGB image into ResNet50 and the Upsampler (which is same as Mask2Former).  ResNet50 outputs feature maps at various resolutions, and these different resolution feature maps attend to each other via deformable attention. This deformable attention is "cross-scale fusion" which is still part of the "within-view" 2D fusion since only pixels from a single view interact with each other but this interaction is across various "feature scales"
