### ISSUE TITLE
Memory Increase

### ISSUE THREAD

**Issue by mingqiJ** [ayushjain1144/odin#17]
Hi, congratulation on your excellent work.

I have tried to train your model. But I find the memory usage of GPU during training is increasing. Do you know why it is?

**Comment by ayushjain1144** [comment]
Hi @mingqiJ , happy to help. Could you provide more details?

- Which script are you running?
- Do you see CPU memory increasing or GPU memory? Which GPU are you using?
- Are there any plots we can look at?

**Comment by mingqiJ** [comment]
Hi, 

I used scripts/scannet/scannet_swin_benchmark.sh. But use bigger image size
The GPU memory is increasing with the iteration increase.

Before the 150 iterations, the print out (log text) shows max_mem: 59464M.
After some iterations, the print out (log text) shows max_mem: 63285M.

In fact, I have added torch.cuda.empty_cache() at the end of the run_step() function in Trainer, otherwise the max_mem increase faster. But adding torch.cuda.empty_cache() dramatically increase the training time.

**Comment by ayushjain1144** [comment]
I see, I wouldn't worry too much about `max_mem` since the unprojected point cloud will have variable surviving points after voxelizations. 

Could you let it run for a couple hours and share with me the wandb link of the run? That would track the GPU memory usage, and we can see if it is monotonically increasing or just randomly varying (which is expected).

**Comment by mingqiJ** [comment]
Okay. I already have one. You mean this?
<img width="1556" alt="image" src="https://github.com/user-attachments/assets/9bbb7bb9-f290-4431-831a-64253c6181f2">

**Comment by ayushjain1144** [comment]
yep :)

I think this looks pretty normal! Doesn't it?

**Comment by mingqiJ** [comment]
Yes. It looks normal. Emm, don't know why it outs of memory last time. Thank you.
Btw, how long you need to train ODIN-Swinb using 2 A100 on scannet dataset?

**Comment by ayushjain1144** [comment]
I think it was about 1.2 days, you can take a look at training logs here: https://huggingface.co/katefgroup/odin_logs/tensorboard

In my experience, max_mem is somewhat mislesding: usually it needs to be decently lower than the max capacity of the GPU. I suspect that's because it displayes average max_memory across several iterations. And because there can be variabilty in point cloud size across iterations, the actual max_memory is larger.

**Comment by mingqiJ** [comment]
I see. Thanks for your answer. 
So if log file said : eta: 1 day, 22:04:47. It means 1 day and 22 hours?

**Comment by ayushjain1144** [comment]
yes

**Comment by mingqiJ** [comment]
Thank you. I don't have any questions.

**Comment by ayushjain1144** [comment]
ok amazing!
