### ISSUE TITLE
Question about MAX_ITER and IMS_PER_BATCH

### ISSUE THREAD

**Issue by mingqiJ** [ayushjain1144/odin#20]
Hi, thanks for your code. I have a question about your training scripts.

I see you set the MAX_ITER and IMS_PER_BATCH in the .sh file. If I decrease the batch size, do I need to increase the iteration?
Like you set 4 IMS_PER_BATCH on 2 gpus and 10000 MAX_ITER.
If I set 2 IMS_PER_BATCH on 2 gpus, do I need to double the MAX_ITER to 20000?

**Comment by ayushjain1144** [comment]
Hi, I typically set them to a "high enough" value so that my training does not get killed pre-maturely; and look at the logs to early-stop when the model converges. 

With half the effective batch size, it should take more iterations but most likely less than twice. In any case, maybe set it to a high enough value, and see when it converges.

**Comment by mingqiJ** [comment]
Hi, thanks for your explanation. Very useful.

**Comment by ayushjain1144** [comment]
i am glad 🙂
