### ISSUE TITLE
Question about USE_GHOST_POINTS.

### ISSUE THREAD

**Issue by mingqiJ** [ayushjain1144/odin#21]
Hi, I see the USE_GHOST_POINTS is use to select whether use mesh point cloud or not.

If I use scannet dataset, and set USE_GHOST_POINTS= False, where to get the instance label for each frame? I only find you get segments from `segment = Image.open(segment_file_names[frame_idx])`. But instance is a little weird.
It is not very clear in your dataloader file.
I see for all ScanNet dataset training, you always set USE_GHOST_POINTS= True.

Thank you.

**Comment by ayushjain1144** [comment]
Hi, 

Yes, we always `USE_GHOST_POINTS=True` for ScanNet (and all other datasets except Ai2Thor). Maybe the confusion is why we say our method is using "sensor" point cloud when we use the `USE_GHOST_POINTS=True` -- when we say we use sensor point cloud, we mean that we produce features on the sensor RGB-D point clouds. We then use "USE_GHOST_POINTS" to transfer these features to mesh point cloud via trilinear interpolation and segment and label there (Page 5, Sensor depth to mesh point cloud feature transfer). This is what we do for baseline methods as well, like Mask3D on sensor point cloud. 

ScanNet only provides instances annotations on the mesh point cloud. They then project these annotations to RGB-D frames, however these labels are sparse and have holes. So they use some 2D post-processing like dilations and closing to fill up the holes. They release some of these annotations on their website -- however, if you visualize these labels in 3D, you will see a lot of noise due to these 2D closing operations and noisy depth. Instead of using those labels, we tried transfering the labels via KNN from mesh to sensor point cloud, and only supervise points which are sufficiently close to the mesh. Then at test time, we transfered predictions from sensor to mesh pointcloud. This gives similar accuracy as the `USE_GHOST_POINTS` -- but we decided to prefer USE_GHOST_POINTS method since it skips the RGB-D label generation and careful loss supervison complexities. 

Let me know if you have any follow up questions, or if the script for generating labels on RGB-D point clouds would be useful to you.

**Comment by mingqiJ** [comment]
Thanks for your explanation. I know you transfer features to mesh point cloud.

Yes, the RGB labels have a lot of noise. But I see in your paper, you mentioned that using RGB labels to train also have similar performance, right?

So I also want to use RGB labels to train the model, not mesh point cloud labels. Could you tell me how to use that on ScanNet dataset? Because I see you didn't provide the preprocess code for ScanNet on RGB labels training.

**Comment by ayushjain1144** [comment]
Its not super trivial, but here are some steps which might help:

- [generate_mask3d_gt_instance_new.txt](https://github.com/user-attachments/files/16478078/generate_mask3d_gt_instance_new.txt): You can refer and use this file to generate GT instance labels, segments and valids on sensor RGB-D images. "segments" is super-voxels of scannet but per image, valids indicate the points which are near a mesh point and thus are safe to supervise. 
- Modify [scannet2coco.py](https://github.com/ayushjain1144/odin/blob/main/data_preparation/scannet/scannet2coco.py) to also save the masks, valids and segments in the json
- I believe the dataloader should work as it is, set `USE_GHOST_POINTS=False` and also use the flags `MODEL.SUPERVISE_SPARSE = True` to only supervise on valid pixels.
- At test time, trilinearly interpolate mask predictions from sensor point cloud to mesh point cloud. you can use something like: https://github.com/ayushjain1144/odin/blob/main/odin/odin_model.py#L630-L638

I do not plan to support this functionality in main code, and I am sorry I would not be able to provide a code that you can run, but happy to help debug if you face any issue / answer any question that may pop up.

**Comment by mingqiJ** [comment]
Thank you. The ScanNet already provide the GT instance labels, segments on RGB-D images. You mean I need to get the valids to make sure which points are safe to supervise?

For testing, have you tried directly predict on the RGB-D point cloud? Not interpolate to mesh point cloud?

**Comment by ayushjain1144** [comment]
I think ScanNet doesn't provide `segments`: these segments is not "segmentation" but they call super-voxelization or cluster of points as segments (like the segments loaded from mesh point cloud here: https://github.com/ayushjain1144/odin/blob/main/odin/data_video/dataset_mapper_scannet.py#L679).

I think you should be able to use their provided instance labels with the valids from this script, but I haven't tried it myself. If you run that script, I would suggest to consider using the labels saved by the script too. 

> For testing, have you tried directly predict on the RGB-D point cloud? Not interpolate to mesh point cloud?

Yes, and I typically used the flag `TEST.EVAL_SPARSE = True` to only evaluate on valid points. Those numbers though are not at all comparable to benchmark numbers because the density/number of points are very different between sensor and mesh point clouds. I don't have any meaningful numbers on sensor point cloud without interpolation that i can share with you for reference since I was trying those  evaluations quite some time back.

**Comment by mingqiJ** [comment]
I see. Thank you. Really? I thought ScanNet provide 2d labels here: 
```
|-- <scanId>_2d-label.zip
    Updated raw 2d projections of aggregated annotation labels as 16-bit pngs with ScanNet label ids
|-- <scanId>_2d-instance.zip
    Updated raw 2d projections of aggregated annotation instances as 8-bit pngs
|-- <scanId>_2d-label-filt.zip
    Updated filtered 2d projections of aggregated annotation labels as 16-bit pngs with ScanNet label ids
|-- <scanId>_2d-instance-filt.zip
    Updated filtered 2d projections of aggregated annotation instances as 8-bit pngs
```

**Comment by ayushjain1144** [comment]
Yeah, they provide 2D instance labels but not "segments" (https://github.com/ScanNet/ScanNet/tree/master/Segmentator). These segments help performance by about 4-5% in mAP for ScanNet benchmark (doesn't affect mAP25 metric). If you don't care about benchmark evaluations, you can skip them

**Comment by mingqiJ** [comment]
I see. What is that means? So these are only the instance segmentation labels, not semantic segmentation labels?
I didn't realize that.

**Comment by ayushjain1144** [comment]
<img width="603" alt="Screenshot 2024-08-03 at 1 26 09 AM" src="https://github.com/user-attachments/assets/e2062281-09c8-47ac-b4ce-5e1ee70c152b">

the "segments" are neither semantic or instance labels. they are simply a bunch of points which are close to each other and have similar normals. For eg., see the attached figure from [here](https://pcl.readthedocs.io/projects/tutorials/en/latest/supervoxel_clustering.html)

A relevant writeup from ScanNet paper which describes "segments"
<img width="437" alt="Screenshot 2024-08-03 at 1 29 18 AM" src="https://github.com/user-attachments/assets/e419b0ee-6497-4528-8d83-4ac4ac580dd5">

**Comment by mingqiJ** [comment]
I see. Thanks for the details. So you mean if I used the code link you send me to get the segment, I will get a better performance, right?

If I used the link you provide for me:[generate_mask3d_gt_instance_new.txt](https://github.com/user-attachments/files/16478078/generate_mask3d_gt_instance_new.txt)

**Comment by ayushjain1144** [comment]
yep, that's right.

**Comment by mingqiJ** [comment]
Hi, thanks for your [generate_mask3d_gt_instance_new.txt](https://github.com/user-attachments/files/16478078/generate_mask3d_gt_instance_new.txt). But I find a function in this code:
`from mask2former_video.modeling.backproject.backproject import backprojector`,

Could you give me this backprojector function? I want to use the exactly same function.

Thank you

**Comment by ayushjain1144** [comment]
Hi, that is the exact same function as this one: https://github.com/ayushjain1144/odin/blob/main/odin/modeling/backproject/backproject.py#L131-L139

(Also, this would print a warning that you are using default scannet intrinsics, that is ok)

**Comment by mingqiJ** [comment]
Hi, I checked this function before. But it seems not exactly same as backprojector in [generate_mask3d_gt_instance_new.txt](https://github.com/user-attachments/files/16478078/generate_mask3d_gt_instance_new.txt):
In the txt file, `rgb_coords = backprojector([rgb_coords.permute(0, 3, 1, 2)], depths[None].float(), poses[None].float())[0][0]`. The inputs are rgb_coords, depths, and poses.

But in https://github.com/ayushjain1144/odin/blob/main/odin/modeling/backproject/backproject.py#L131-L139, the inputs are depths, poses, intrinsics

**Comment by ayushjain1144** [comment]
[backproject.txt](https://github.com/user-attachments/files/16503377/backproject.txt)

Sure, here is the original file.

**Comment by mingqiJ** [comment]
Thank you. It is very useful!

**Comment by mingqiJ** [comment]
Hi, I have more questions, this is the files saved using [generate_mask3d_gt_instance_new.txt](https://github.com/user-attachments/files/16478078/generate_mask3d_gt_instance_new.txt)
`instance_sep.png, valids.png, segments.png`

So, when I use `scannet2coco.py` file to save them in the json, 
```
coco_output = {
        "info": INFO,
        "licenses": LICENSES,
        "categories": CATEGORIES if not scannet200 else CATEGORIES_200,
        "images": [],
        "depths": [],
        "poses": [],
        "valids": [],
        "segments": [],
        "annotations": []
    }
```
`"valids"` is `valids.png`, `"segments"` is `segments.png`, how about `instance_sep.png`? Should be put in `"annotations"`?

**Comment by ayushjain1144** [comment]
[scannet2coco_new.txt](https://github.com/user-attachments/files/16511878/scannet2coco_new.txt)

Zip of the branch where I tried running these experiments if that helps: 
[Mask2Former3D-segment_ghost.zip](https://github.com/user-attachments/files/16511913/Mask2Former3D-segment_ghost.zip)

I haven't touched this code for an year now, I would just use it for reference but wouldn't really try running this code as it can have bugs.

**Comment by mingqiJ** [comment]
Thank you. I already mimic ai2thor2coco.py. It didn't work because I don't use LEARNING_MAP20. Thanks for your new code.

I think your training code can directly support 2d labels training (USE_GHOST_POINTS=False), right?

**Comment by ayushjain1144** [comment]
Yes, it should directly support it

**Comment by mingqiJ** [comment]
Emm, I have set `USE_GHOST_POINTS=False`, but it takes errors:
```
ODIN/odin/odin_model.py", line 551, in adjust_masks_for_highres
    targets[i]['voxel_masks'].float(), segments[i][:targets[i]['voxel_masks'].shape[1]][None], dim=1
TypeError: 'NoneType' object is not subscriptable
```
The `segments` is `None`. It seems that you didn't give the correct things to the `segments`.

In `forward` and `load_3d_data`, the code just give `None` to the `segments` if `USE_GHOST_POINTS=False`
```
depths, poses, intrinsics, valids, segments = None, None, None, None, None
depths, poses, valids, segments, intrinsics, multiview_data = self.load_3d_data(
            batched_inputs,
            images_shape=[bs, v, H_padded, W_padded],
            decoder_3d=decoder_3d
        )        
```

I don't think the code can directly work with `USE_GHOST_POINTS=False`.

Could you help me to check it?

**Comment by ayushjain1144** [comment]
I see, yes, i think the segments are currently returned as None. You can modify load_3d_data function to also load the segments (the zip I sent you should help). 

But unfortunately, I wouldn't be able to allocate time to actively debug and push a working code, since I don't intend to support no ghost_point version in the public code. But if you get stuck, please don't hesitate to message, and I will try to help in whatever way possible for me.

**Comment by mingqiJ** [comment]
Okay. Thank you. I have checked .zip file. It also didn't load `segments`, it directly give `None` to `segments`. It seems that I need to write one by my self. But I am not sure the shape/format used in `segments`. Directly follow the `valids` shape/format? `(bs, v, h, w)`

**Comment by ayushjain1144** [comment]
[Mask2Former3D-new_segments.zip](https://github.com/user-attachments/files/16514635/Mask2Former3D-new_segments.zip)

You're right, i rechecked, i added the segments functionality in another branch that i am attaching (you will also see something related to "VALID_FEATURE" flag, that didn't help and you can ignore).

But, in anycase, i would recommend running first without segments and get some reasonable performance; then add segments.

**Comment by mingqiJ** [comment]
Thank you. I have tried to add segments, but it still takes errors in `odin_transformer_decoder.py`:
```
 # voxelize (mask features are already voxelized)
 assert mask_features_xyz.shape[-2] == mask_features.shape[-1]
```
I have checked the code, I don't think mask features are already voxelized before the `odin_transformer_decoder.py`.

**Comment by mingqiJ** [comment]
Hi, I also have a question in the load_3d_data function. Why you downsample the segments?
```
# downsample the segments
segments = F.interpolate(
                    segments.float(), scale_factor=0.25, mode="nearest"
                )
```
In the code you give me.

**Comment by mingqiJ** [comment]
Hi, I have a question about using 2d labels to train. 

I see you use supervise sparseto train the model on ai2thor dataset. So for this dataset, you train using 2d labels and also evaluate on 2d labels?

**Comment by ayushjain1144** [comment]
Yes! (But they are not "really" 2D labels, they are 3D labels since the same 3D chair has a consistent instance ID across the RGB frames. Its just that instance labels are now of shape N X V X H X W where N=number of instances, V=number of views, H, W = height and width of images; instead of scannet where the labels are of shape N X M where M=number of points on ScanNet point cloud)

**Comment by mingqiJ** [comment]
I see. So for ai2thor dataset, you train it using the 2d labels projected from 3d labels and with supervise sparse. 
And for testing, you also evaluate using the 2d labels projected from 3d labels, it is like evaluate on each image, and also evaluate sparse?

**Comment by ayushjain1144** [comment]
No, both the supervision and evaluation is in 3D: i.e. on a point cloud of shape (V * H * W), 3 (i.e flattening the multiview RGB-D instances)

Some of the depth locations are invalid, so more precisely the supervision and evaluation is only on valid points out of total V * H * W points (by simply indexing the points with valids: https://github.com/ayushjain1144/odin/blob/main/odin/data_video/scannet_3d_eval.py#L122)

**Comment by mingqiJ** [comment]
I see. Thank you. I can think that is 3d projection from all multiview RGB-D frames.

Did you evaluate on all points? not only valid points.

**Comment by ayushjain1144** [comment]
only on valid points for both our method and baselines. (However, i didn't notice much difference in absolute numbers)

**Comment by mingqiJ** [comment]
Thank you. I see when you train on ai2thor, you set `HIGH_RES_SUBSAMPLE True` and `HIGH_RES_INPUT True`. Do you think I need this when I train use RGB-D points labels on ScanNet?

**Comment by ayushjain1144** [comment]
It saves some GPU memory, I would use it if the `INPUT.IMAGE_SIZE` is 512. I don't think it would benefit much when the size is 256. But its not something critical that would help in performance

**Comment by mingqiJ** [comment]
Thank you. RGBD points cloud supervise work.

**Comment by ayushjain1144** [comment]
Amazing! Glad to hear that 🙂
