### ISSUE TITLE
How to inference?

### ISSUE THREAD

**Issue by 21yrm** [ayushjain1144/odin#22]
1. odin only takes images as input without including any point cloud file?
2. the output of odin is 3d masks which are in point cloud format?
3. could you please share a demo so that we can quickly run?
Thank u~

**Comment by ayushjain1144** [comment]
1. Posed RGB-D images (so, RGB, depth, intrinsics, and camera poses)
2. The output is N X V X H X W masks and N classes; where N are the number of predictions, V=number of images, H/W=height and width of the images. 
3. I don't have a demo yet in the code, and I don't anticipate it to be available anytime soon due to my schedule. I would encourage you to take a look at ScanNet/AI2THOR RGB-D data, and formatting your data like that should let you run the inference quickly
