### ISSUE TITLE
Difference between several point cloud?

### ISSUE THREAD

**Issue by AaronXenos** [ayushjain1144/odin#9]
In the paper, three types are discussed in Experiments: **rendered, sensor, and mesh-sampled** . 
What's the differences? 
Are they just different ways to process the dataset? sensor use .sens file and mesh-sampled use .ply file?

**Comment by ayushjain1144** [comment]
Good question:

mesh-sampled point cloud: that comes from .ply
sensor point cloud: that comes from unprojecting the RGB-D images from the .sens 
rendered point cloud: typically obtained by rendering the mesh into RGB images and depths from the camera poses in the recorded RGB-D stream (for eg. from the poses in .sens files). These RGB-D images are more aligned with the mesh point cloud (since its rendered from it) but can have holes and rendering artifacts in the RGB and depth images. 

Btw just FYI, sensor point clouds can look very different from mesh point clouds. I am attaching an example. Notice how large regions of the scene is missing from mesh point cloud because scannet post-processing dropped those regions. Besides these large differences, there are more subtle misalignments. 

<img width="1413" alt="Screenshot 2024-05-01 at 10 28 16 AM" src="https://github.com/ayushjain1144/odin/assets/28894174/7a48fbc0-c04a-4755-b62e-c4bc8c372450">

**Comment by AaronXenos** [comment]
> Good question:
> 
> mesh-sampled point cloud: that comes from .ply sensor point cloud: that comes from unprojecting the RGB-D images from the .sens rendered point cloud: typically obtained by rendering the mesh into RGB images and depths from the camera poses in the recorded RGB-D stream (for eg. from the poses in .sens files). These RGB-D images are more aligned with the mesh point cloud (since its rendered from it) but can have holes and rendering artifacts in the RGB and depth images.
> 
> Btw just FYI, sensor point clouds can look very different from mesh point clouds. I am attaching an example. Notice how large regions of the scene is missing from mesh point cloud because scannet post-processing dropped those regions. Besides these large differences, there are more subtle misalignments.
> 
> <img alt="Screenshot 2024-05-01 at 10 28 16 AM" width="1413" src="https://private-user-images.githubusercontent.com/28894174/332266378-7a48fbc0-c04a-4755-b62e-c4bc8c372450.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNjM4MTksIm5iZiI6MTcxNjI2MzUxOSwicGF0aCI6Ii8yODg5NDE3NC8zMzIyNjYzNzgtN2E0OGZiYzAtYzA0YS00NzU1LWI2MmUtYzRiYzhjMzcyNDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDAzNTE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NWFhMTE5MjdjMDdiMDAyYmUwOWFiZjFkMzE4NzFkNDFiNWEwMzcxMGU3NWMxOTk1MzkzNGZjNTg2YzI0NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hYTtfz76s4gJI9CYhluuWl-mBPq94Ok9vZ9pKIdW8Ak">

Thank you very much. I got it.
